# ~/.config/starship.toml

# Wait a bit longer than the default 500ms for commands to execute. Node and git
# timeout rather frequently.
command_timeout = 5000

[nodejs]
symbol = "⬢ " # https://github.com/starship/starship/issues/2546
